export default [
  {
    alameda: "Alameda",
    alpine: "Alpine",
    amador: "Amador",
    butte: "Butte",
    calaveras: "Calaveras",
    colusa: "Colusa",
    "contra-costa": "Contra Costa",
    "del-norte": "Del Norte",
    "el-dorado": "El Dorado",
    fresno: "Fresno",
    glenn: "Glenn",
    humboldt: "Humboldt",
    imperial: "Imperial",
    inyo: "Inyo",
    kern: "Kern",
    kings: "Kings",
    lake: "Lake",
    lassen: "Lassen",
    "los-angeles": "Los Angeles",
    madera: "Madera",
    marin: "Marin",
    mariposa: "Mariposa",
    mendocino: "Mendocino",
    merced: "Merced",
    modoc: "Modoc",
    mono: "Mono",
    monterey: "Monterey",
    napa: "Napa",
    nevada: "Nevada",
    orange: "Orange",
    placer: "Placer",
    plumas: "Plumas",
    riverside: "Riverside",
    sacramento: "Sacramento",
    "san-benito": "San Benito",
    "san-bernardino": "San Bernardino",
    "san-diego": "San Diego",
    "san-francisco": "San Francisco",
    "san-joaquin": "San Joaquin",
    "san-luis-obispo": "San Luis Obispo",
    "san-mateo": "San Mateo",
    "santa-barbara": "Santa Barbara",
    "santa-clara": "Santa Clara",
    "santa-cruz": "Santa Cruz",
    shasta: "Shasta",
    sierra: "Sierra",
    siskiyou: "Siskiyou",
    solano: "Solano",
    sonoma: "Sonoma",
    stanislaus: "Stanislaus",
    sutter: "Sutter",
    tehama: "Tehama",
    trinity: "Trinity",
    tulare: "Tulare",
    tuolumne: "Tuolumne",
    unassigned: "Unassigned",
    ventura: "Ventura",
    yolo: "Yolo",
    yuba: "Yuba"
  }
];
