export default [
  { value: "alameda", text: "Alameda" },
  { value: "alpine", text: "Alpine" },
  { value: "amador", text: "Amador" },
  { value: "butte", text: "Butte" },
  { value: "calaveras", text: "Calaveras" },
  { value: "colusa", text: "Colusa" },
  { value: "contra-costa", text: "Contra Costa" },
  { value: "del-norte", text: "Del Norte" },
  { value: "el-dorado", text: "El Dorado" },
  { value: "fresno", text: "Fresno" },
  { value: "glenn", text: "Glenn" },
  { value: "humboldt", text: "Humboldt" },
  { value: "imperial", text: "Imperial" },
  { value: "inyo", text: "Inyo" },
  { value: "kern", text: "Kern" },
  { value: "kings", text: "Kings" },
  { value: "lake", text: "Lake" },
  { value: "lassen", text: "Lassen" },
  { value: "los-angeles", text: "Los Angeles" },
  { value: "madera", text: "Madera" },
  { value: "marin", text: "Marin" },
  { value: "mariposa", text: "Mariposa" },
  { value: "mendocino", text: "Mendocino" },
  { value: "merced", text: "Merced" },
  { value: "modoc", text: "Modoc" },
  { value: "mono", text: "Mono" },
  { value: "monterey", text: "Monterey" },
  { value: "napa", text: "Napa" },
  { value: "nevada", text: "Nevada" },
  { value: "orange", text: "Orange" },
  { value: "placer", text: "Placer" },
  { value: "plumas", text: "Plumas" },
  { value: "riverside", text: "Riverside" },
  { value: "sacramento", text: "Sacramento" },
  { value: "san-benito", text: "San Benito" },
  { value: "san-bernardino", text: "San Bernardino" },
  { value: "san-diego", text: "San Diego" },
  { value: "san-francisco", text: "San Francisco" },
  { value: "san-joaquin", text: "San Joaquin" },
  { value: "san-luis-obispo", text: "San Luis Obispo" },
  { value: "san-mateo", text: "San Mateo" },
  { value: "santa-barbara", text: "Santa Barbara" },
  { value: "santa-clara", text: "Santa Clara" },
  { value: "santa-cruz", text: "Santa Cruz" },
  { value: "shasta", text: "Shasta" },
  { value: "sierra", text: "Sierra" },
  { value: "siskiyou", text: "Siskiyou" },
  { value: "solano", text: "Solano" },
  { value: "sonoma", text: "Sonoma" },
  { value: "stanislaus", text: "Stanislaus" },
  { value: "sutter", text: "Sutter" },
  { value: "tehama", text: "Tehama" },
  { value: "trinity", text: "Trinity" },
  { value: "tulare", text: "Tulare" },
  { value: "tuolumne", text: "Tuolumne" },
  { value: "unassigned", text: "Unassigned" },
  { value: "ventura", text: "Ventura" },
  { value: "yolo", text: "Yolo" },
  { value: "yuba", text: "Yuba" }
];
